### ISSUE TITLE
redux 

### ISSUE THREAD

**Issue by mikepc** [thundermiracle/next-mui-helper#15]
By wrapping up everything and without a redux example, the struggle is real in figuring out where/how to manage the redux store, or where to wrap withReduxSaga.  Where it might be blatantly obvious to you, coming from the outside.. not so much.

Could you please include an example that implements at least redux and redux-saga?

**Comment by thundermiracle** [comment]
@mikepc makeNextDocument() returns next.js' Document component for inherit from.
You can add redux's provider there.
I'm not familiar with redux saga, but I'll add a with-redux example.

**Comment by thundermiracle** [comment]
@mikepc 
The example is here:
https://github.com/thundermiracle/next-mui-helper/tree/master/examples/withRedux
