### ISSUE TITLE
Support Material UI 4.0.0

### ISSUE THREAD

**Issue by adamsoffer** [thundermiracle/next-mui-helper#17]
Thank you for this amazing package! Just a heads up - I'm getting the following error when using with material `4.0.0`:

`Module not found: Can't resolve '@material-ui/core/styles/createGenerateClassName'`

**Comment by thundermiracle** [comment]
@adamsoffer My projects are not using material 4.0 yet, but I'll check this issue ASAP.

**Comment by thundermiracle** [comment]
@adamsoffer The error occurred because material-ui 4.0 was refactored to wrap the old getContext() into the ServerStyleSheets(). 
I've just updated this package to 3.0.0 to support material-ui 4.0.
You can have a try.

**Comment by adamsoffer** [comment]
Can confirm fix works! Thanks @thundermiracle 😃
